#################
# General Setting
#################
# Experiment name, if the experiment name has the word debug, it will enter debug mode
name: F2M_res18_cifar_5shots_30bases_10test_{UDF}{D:B0.02}_debug
# The type of model used, usually the class name of the model defined in the `methods` directory
model_type: MTNBModel
# gpu
gpu: '1'
# Random seed
manual_seed: 1997
use_cosine: false
Random: false

#################################
# The settings for the dataset and data loader
#################################
transformer_agu:
  - type: RandomCrop
    size: 32
    padding: 4
  - type: RandomHorizontalFlip
  - type: ToTensor
  - type: Normalize
    mean: !!python/tuple [ 0.5071,  0.4866,  0.4409 ]
    std: !!python/tuple [ 0.2009,  0.1984,  0.2023 ]

transformer:
  - type: ToTensor
  - type: Normalize
    mean: !!python/tuple [ 0.5071,  0.4866,  0.4409 ]
    std: !!python/tuple [ 0.2009,  0.1984,  0.2023 ]


datasets:
  # The important information of dataset
  train:
    name: cifar-100
    type: NormalDataset
    total_classes: 100
    dataroot: DataSet/cifar-100/train
    aug: true
    pre_load: false
    # Number of processes read by the data loader per GPU
    num_worker_per_gpu: 8
    # Batch size
    batch_size: ~
    pin_memory: true

    sampler:
      type: TaskSampler
      num_samples: 5

  val:
    name: cifar-100
    type: NormalDataset
    total_classes: 100
    dataroot: DataSet/cifar-100/test
    aug: false
    pre_load: false
    # Number of processes read by the data loader per GPU
    num_worker_per_gpu: 8
    sampler:
      type: ~

  test:
    name: cifar-100
    type: NormalDataset
    total_classes: 100
    dataroot: DataSet/cifar-100/test
    aug: false
    pre_load: false
    # Number of processes read by the data loader per GPU
    num_worker_per_gpu: 8
    sampler:
      type: ~

#####################
# The following is the setup of the network structure
#####################
network_g:
  type: Resnet20_cifar_small
  num_classes: 60
  adopt_classifier: false
  flatten: true

######################################
# The following are the paths
######################################
path:
  # Base model path, need models ending in pth
  pretrain_model_g: ./exp/cifar-100_bases60/CFRPModel_res18_cifar_{DB:4}{sfc4:0.01}{PTFix:1.0}{rdt2}{BathchSize:256}{std:2.0}_60base_wandb_001/models/best_net_latest.pth
#  pretrain_prototypes: ./exp/cifar-100_bases60_noBuffer/CFRPModel_res18_small_cifar_baseline_cudnnFix_60base_wandb_001/models/pretrain_prototypes.pt
#  base_model: ./exp/cifar-100_bases60_noBuffer/CFRPModel_res18_small_cifar_baseline_cudnnFix_60base_wandb_001/models/best_net_latest.pth
  base_model: ./exp/cifar-100_bases60/CFRPModel_res18_cifar_{DB:4}{sfc4:0.01}{PTFix:1.0}{rdt2}{BathchSize:256}{std:2.0}_60base_wandb_001/models/best_net_latest.pth
  strict_load: false


#################
# The following is the training setup
#################
train:
  # Optimizer
  optim_g:
    # The type of optimizer
    type: SGD
    ##### The following properties are flexible and have different settings depending on the optimizer
    # learning rate
    lr: !!float 1e-2
    weight_decay: !!float 5e-4
    # momentum
    momentum: !!float 0.9

  # The setting of scheduler
  scheduler:
    # The type of scheduler
    type: MultiStepLR
    #### The following properties are flexible, depending on the learning rate Scheduler has different settings
    #
    # milestones, using epoch to represent the points to decay the learning rate
    milestones: [1000]

    # gama
    gamma: !!float 1e-5

  # whether fine_tune
  fine_tune: true

  random_noise:
    distribution:
      type: DiscreteBeta
    type: suffix_conv_weight
    num_layers: 4
    low: 0.1
    high: 5.0
    reduction_factor: 4
    bound_value: 0.01
    random_times: 0

  clamping: true
  rounding: true

  fine_tune_epoch: 6

  max_steps: 1
  ratio: 1
  novel_exemplars: 5
  # The number of warm up iteration, if -1, means no warm up
  warmup_iter: -1  # no warm up
  # number of base classes
  bases: 60
  # number of tasks for incremental few-shot learning
  tasks: 9
  # number of shots for incremental few-shot learning
  shots: 5
  # number of tests for incremental few-shot learning
  num_test: 10

  pn_opt:
    type: IncrementalPTFixPNLoss
    w: 1.0
    omega: 1.0
    n_shots: 5
    use_cosine: false

#######################
# The following are the settings for Validation
#######################
val:
  # The frequency of validation
  val_freq: 5
  test_type: NCM

####################
# The following are the settings for Logging
####################
logger:
  # Frequency of loggers printed on the screen according to iteration
  print_freq: 1
  # Whether to use tensorboard logger

  use_tb_logger: true
  # Whether to use wandb logger
  wandb:
    # The default is None, i.e. wandb is not used.
    project: FIL-Noise-Cifar-Incremental-Results
    # If it is resume, you can enter the last wandb id, then the log can be connected
    resume_id: ~

