#################
# General Setting
#################
# Experiment name, if the experiment name has the word debug, it will enter debug mode
name: FSIL_FSLLModel_res18_cifar_baseline_5shots_30base_2tasks_{UDF}_wandb_debug
# The type of model used, usually the class name of the model defined in the `methods` directory
model_type: FSLLModel
# gpu
gpu: '1'
# Random seed
manual_seed: 1997
use_cosine: false
Random: false

#################################
# The settings for the dataset and data loader
#################################
transformer_agu:
  - type: RandomResizedCrop
    size: 84
  - type: ColorJitter
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4
  - type: RandomHorizontalFlip
  - type: ToTensor
  - type: Normalize
    mean: !!python/tuple [0.485, 0.456, 0.406]
    std: !!python/tuple [0.229, 0.224, 0.225]

transformer:
  - type: Resize
    size: 92
  - type: CenterCrop
    size: 84
  - type: ToTensor
  - type: Normalize
    mean: !!python/tuple [ 0.485, 0.456, 0.406 ]
    std: !!python/tuple [ 0.229, 0.224, 0.225 ]


datasets:
  # The important information of dataset
  train:
    name: miniImageNet
    type: NormalDataset
    total_classes: 100
    dataroot: ./DataSet/FSIL_miniImageNet/miniimagenet/train
    aug: true
    pre_load: false
    # Number of processes read by the data loader per GPU
    num_worker_per_gpu: 8
    # Batch size
    batch_size: 25
    pin_memory: true

    sampler:
      type: TaskSampler
      num_samples: 5

  val:
    name: miniImageNet
    type: NormalDataset
    total_classes: 100
    dataroot: ./DataSet/FSIL_miniImageNet/miniimagenet/test
    aug: false
    pre_load: false
    # Number of processes read by the data loader per GPU
    num_worker_per_gpu: 8
    sampler:
      type: ~

  test:
    name: miniImageNet
    type: NormalDataset
    total_classes: 100
    dataroot: ./DataSet/FSIL_miniImageNet/miniimagenet/test
    aug: false
    pre_load: true
    # Number of processes read by the data loader per GPU
    num_worker_per_gpu: 8
    sampler:
      type: ~

#####################
# The following is the setup of the network structure
#####################
network_g:
  type: Resnet18_softmax
  Embed_dim: 512
  pretrained: false
  norm: false
  num_classes: 60
  adopt_classifier: false
  addition_net: false
  flatten: true
  cut_at_pooling: false

######################################
# The following are the paths
######################################
path:
  pretrain_model_g: ./exp/miniImageNet_bases60/FSIL_CFRPModel_res18_miniImageNet_normalDataset_baseline_60base_wandb_001/models/best_net_latest.pth
  # Base model path, need models ending in pth
  base_model: ./exp/miniImageNet_bases60/FSIL_CFRPModel_res18_miniImageNet_normalDataset_baseline_60base_wandb_001/models/best_net_latest.pth
  strict_load: false


#################
# The following is the training setup
#################
train:
  # Optimizer
  optim_g:
    # The type of optimizer
    type: SGD
    ##### The following properties are flexible and have different settings depending on the optimizer
    # learning rate
    lr: !!float 1e-3
    weight_decay: !!float 5e-4
    # momentum
    momentum: !!float 0.9

  # The setting of scheduler
  scheduler:
    # The type of scheduler
    type: MultiStepLR
    #### The following properties are flexible, depending on the learning rate Scheduler has different settings
    #
    # milestones, using epoch to represent the points to decay the learning rate
    milestones: [ !!python/object/apply:eval [ 80 * 2 ]]

    # gama
    gamma: 0.1

  # whether fine_tune
  fine_tune: true
  # The number of epoch
  fine_tune_epoch: 15

  threshold: 0.16
  # The number of warm up iteration, if -1, means no warm up
  warmup_iter: -1  # no warm up
  # number of base classes
  bases: 60
  # number of tasks for incremental few-shot learning
  tasks: 9
  # number of shots for incremental few-shot learning
  shots: 5
  novel_exemplars: 5
  # number of tests for incremental few-shot learning
  num_test: 3
  # losses
  metric_opt:
    type: TripletLossNoHardMining
    margin: !!float 0.0
    num_instances: 5
  pn_opt:
    type: IncrementalPTFixPNLoss
    w: 1.0
    omega: 1.0
    n_shots: 5
    use_cosine: true
  regularization:
    type: IncrementalNetworkFixLoss
    w: 5.0


#######################
# The following are the settings for Validation
#######################
val:
  # The frequency of validation
  val_freq: 200
  test_type: NCM
  p_norm: ~

####################
# The following are the settings for Logging
####################
logger:
  # Frequency of loggers printed on the screen according to iteration
  print_freq: 2
  # Whether to use tensorboard logger

  use_tb_logger: true
  # Whether to use wandb logger
  wandb:
    # The default is None, i.e. wandb is not used.
    project: FIL-Noise-Cifar-Incremental
    # If it is resume, you can enter the last wandb id, then the log can be connected
    resume_id: ~

